image_width: 752
image_height: 480
camera_name: bluefox_front
camera_matrix:
  rows: 3
  cols: 3
  data: [498.163746, 0.0, 381.838916, 0.0, 498.276943, 265.479122, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.411033, 0.122807, 0.001905, -0.000839, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [340.118927, 0, 383.435780, 0, 0, 439.753906, 273.814459, 0, 0, 0, 1, 0]
