world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 50.0764041
  origin_y: 14.4180359

safety_area:

  enabled: true

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "latlon_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: [
      50.0765653, 14.4178914,
      50.0762102, 14.4179722,
      50.0763015, 14.4181847,
      50.0765825, 14.4181411,
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 4.0
    min_z: 1.0
